=== djordjenrt5117/ProveraZnanja/magacin.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Artikli (Artikal)+>
<!ELEMENT Artikal (Naziv,DatumIzrade,Cena,KompanijaProdavca,(Email)+)>

<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv id ID #REQUIRED>

<!ELEMENT DatumIzrade (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena tip (dinar|euro) "dinar">

<!ELEMENT KompanijaProdavca (ImeKompanije,(Adresa)+)>
<!ELEMENT ImeKompanije (#PCDATA)>
<!ELEMENT Adresa (#PCDATA)>

<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email tip (privatni|sluzbeni) #REQUIRED>

=== djordjenrt5117/ProveraZnanja/magacin.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Artikli SYSTEM "magacin.dtd">

<Artikli>
    <Artikal>
        <Naziv id="id_1">asdf</Naziv>

        <DatumIzrade>
            <Dan>11</Dan>
            <Mesec>2</Mesec>
            <Godina>2019</Godina>
        </DatumIzrade>
        <Cena tip="dinar">100</Cena>
        <KompanijaProdavca>
            <ImeKompanije>ASSDASD</ImeKompanije>
            <Adresa>asfasfasfa</Adresa>
        </KompanijaProdavca>

        <Email tip="privatni">asfasasf@gmail.com</Email>
        <Email tip="sluzbeni">dddddd@gmail.com</Email>

    </Artikal>

    <Artikal>
        <Naziv id="id_2">fasfasff</Naziv>

        <DatumIzrade>
            <Dan>3</Dan>
            <Mesec>12</Mesec>
            <Godina>2019</Godina>
        </DatumIzrade>
        <Cena tip="euro">100</Cena>
        <KompanijaProdavca>
            <ImeKompanije>ASSDASD</ImeKompanije>
            <Adresa>ffffff</Adresa>
            <Adresa>dddddd</Adresa>
        </KompanijaProdavca>

        <Email tip="sluzbeni">asfasasf@gmail.com</Email>

    </Artikal>
</Artikli>
